# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poof < Formula
  desc "Build, deploy, and manage Solana dApps on poof.new"
  homepage "https://poof.new"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.6/poof-cli_0.1.6_darwin_amd64.tar.gz"
      sha256 "dbfca45eee34f84fae5660e73e8b7c75149d1e1f290ee834d3f700ab39f534d7"

      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.6/poof-cli_0.1.6_darwin_arm64.tar.gz"
      sha256 "2d9ec5d576195120084b82eba9382da73958dc5878cab81d7731054ec3fc3e44"

      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.6/poof-cli_0.1.6_linux_amd64.tar.gz"
      sha256 "12177fe84ce6f013291242aa6108f1d9c6d367cebcd95a8d3bd4ce640271e8c7"
      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.6/poof-cli_0.1.6_linux_arm64.tar.gz"
      sha256 "7aa8a6d4814e4e769e9ba77832358f5414b455194a8e1b7b1efc65507ca45e1d"
      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  test do
    system "#{bin}/poof", "version"
  end
end
