# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PoofCli < Formula
  desc "Build, deploy, and manage Solana dApps on poof.new"
  homepage "https://poof.new"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.0/poof-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "33d5cc479743c36fdd6c1e0af60fa84478646af906ba54021351c18d1e7beca2"

      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.0/poof-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "230db869ce011c96ffbb2f134d1f0b34f1aad976f5a50eb1be585f062c98441d"

      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.0/poof-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "69e22ff7dc2e4564bc54d9c6825ec7b31c5c89102265e3e63916f52be1d808d5"
      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.0/poof-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "188d5ca685cec7fd20141cc13022aa046a1014ea3b18acc994f0ef58b0256cad"
      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  test do
    system "#{bin}/poof", "version"
  end
end
