# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poof < Formula
  desc "Build, deploy, and manage Solana dApps on poof.new"
  homepage "https://poof.new"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.3/poof-cli_0.1.3_darwin_amd64.tar.gz"
      sha256 "5a42812789218a89f99bc8e2d267f33ae7f7e4b56021438b70708d028de46dda"

      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.3/poof-cli_0.1.3_darwin_arm64.tar.gz"
      sha256 "a584bb357dee67286a83d7114308295dd869a5d07c8418fc05458e466389d9cf"

      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.3/poof-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "81c210f3d771f8ff48988282e5a2fe58bb6700ed99931695a785103ab22b5603"
      define_method(:install) do
        bin.install "poof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poofdotnew/poof-cli/releases/download/v0.1.3/poof-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "1956b42d4c67c7ebea233688e6b7a14d5d0c4185f0e51ee6a8d33d86ebab7c58"
      define_method(:install) do
        bin.install "poof"
      end
    end
  end

  test do
    system "#{bin}/poof", "version"
  end
end
